# Практическое задание №2 по теме "Создание признакового пространства".

Загрузка данных:

In [1]:
import pickle
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn import model_selection, preprocessing, linear_model
from sklearn.metrics import accuracy_score
from sklearn.decomposition import PCA

with open('/content/drive/MyDrive/data.pickle', 'rb') as f:
    df = pickle.load(f)

df.head()

,id,label,tweet,tweet_token,tweet_token_filtered,tweet_stemmed,tweet_lemmatized
0,1,0.0,when father is dysfunctional and is so selfish...,"[when, father, is, dysfunctional, and, is, so,...","[father, dysfunctional, selfish, drags, kids, ...","[father, dysfunct, selfish, drag, kid, dysfunc...","[father, dysfunctional, selfish, drag, kid, dy..."
1,2,0.0,thanks for lyft credit cannot use cause they d...,"[thanks, for, lyft, credit, can, not, use, cau...","[thanks, lyft, credit, use, cause, offer, whee...","[thank, lyft, credit, use, caus, offer, wheelc...","[thank, lyft, credit, use, cause, offer, wheel..."
2,3,0.0,bihday your majesty,"[bihday, your, majesty]","[bihday, majesty]","[bihday, majesti]","[bihday, majesty]"
3,4,0.0,model love yoyou take with yoyou all the time ...,"[model, love, yoyou, take, with, yoyou, all, t...","[model, love, yoyou, take, yoyou, time, yoyour]","[model, love, yoyou, take, yoyou, time, yoyour]","[model, love, yoyou, take, yoyou, time, yoyour]"
4,5,0.0,factsguide society now motivation,"[factsguide, society, now, motivation]","[factsguide, society, motivation]","[factsguid, societi, motiv]","[factsguide, society, motivation]"

Переводим списки в столбцах tweet_stemmed и tweet_lemmatized в str:

In [2]:
for i in range(len(df['tweet_stemmed'])):
    out_str = " "
    strr = df['tweet_stemmed'][i]
    df['tweet_stemmed'][i] = out_str.join(strr)
    out_str = " "
    strr = df['tweet_lemmatized'][i]
    df['tweet_lemmatized'][i] = out_str.join(strr)

<ipython-input-2-9ded9203f206>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tweet_stemmed'][i] = out_str.join(strr)
<ipython-input-2-9ded9203f206>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tweet_lemmatized'][i] = out_str.join(strr)

Машок слов с помощью CountVectorizer:

In [3]:
count_vectorizer = CountVectorizer(max_df = 0.9, max_features = 1000, stop_words='english')

bag_of_words = count_vectorizer.fit_transform(df['tweet_stemmed'])

feature_names = count_vectorizer.get_feature_names_out()
BoW_Cv_ts = pd.DataFrame(bag_of_words.toarray(), columns = feature_names)
BoW_Cv_ts.head()

,abl,absolut,accept,account,act,action,actor,actual,ad,adapt,...,yo,yoga,york,young,youtub,yoyou,yoyour,yoyoy,yr,yummi
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,2,1,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
bag_of_words = count_vectorizer.fit_transform(df['tweet_lemmatized'])

feature_names = count_vectorizer.get_feature_names_out()
BoW_Cv_tl = pd.DataFrame(bag_of_words.toarray(), columns = feature_names)
BoW_Cv_tl.head()

,able,absolutely,accept,account,act,action,actor,actually,adapt,add,...,yoga,york,young,youtube,yoyou,yoyour,yoyoyou,yr,yrs,yummy
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,2,1,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Мешок слов с помощью TfidfVectorizer:

In [5]:
tfidf_vectorizer = TfidfVectorizer(max_df = 0.9, max_features = 1000, stop_words='english')
values = tfidf_vectorizer.fit_transform(df['tweet_stemmed'])

feature_names = tfidf_vectorizer.get_feature_names_out()
BoW_Tf_ts=pd.DataFrame(values.toarray(), columns = feature_names)
BoW_Tf_ts.head()

,abl,absolut,accept,account,act,action,actor,actual,ad,adapt,...,yo,yoga,york,young,youtub,yoyou,yoyour,yoyoy,yr,yummi
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.743324,0.391965,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0

In [6]:
values = tfidf_vectorizer.fit_transform(df['tweet_lemmatized'])

feature_names = tfidf_vectorizer.get_feature_names_out()
BoW_Tf_tl=pd.DataFrame(values.toarray(), columns = feature_names)
BoW_Tf_tl.head()

,able,absolutely,accept,account,act,action,actor,actually,adapt,add,...,yoga,york,young,youtube,yoyou,yoyour,yoyoyou,yr,yrs,yummy
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.742601,0.391988,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0

Проверка на корпусе:

In [7]:
# Загружаем данные
data = open('/content/drive/MyDrive/corpus').read()
labels, texts = [], []
for i, line in enumerate(data.split("\n")):
    content = line.split()
    labels.append(content[0])
    texts.append(" ".join(content[1:]))

# создаем df
trainDF = pd.DataFrame()
trainDF['text'] = texts
trainDF['label'] = labels
trainDF.head(5)

                                                text       label
0  Stuning even for the non-gamer: This sound tra...  __label__2
1  The best soundtrack ever to anything.: I'm rea...  __label__2
2  Amazing!: This soundtrack is my favorite music...  __label__2
3  Excellent Soundtrack: I truly like this soundt...  __label__2
4  Remember, Pull Your Jaw Off The Floor After He...  __label__2

Разделение данных:

In [8]:
train_x, valid_x, train_y, valid_y = model_selection.train_test_split(trainDF['text'], trainDF['label'])

encoder = preprocessing.LabelEncoder()
train_y = encoder.fit_transform(train_y)
valid_y = encoder.fit_transform(valid_y)

In [9]:
count_vectorizer = CountVectorizer(max_df = 0.9, max_features = 1000, stop_words='english')
tfidf_vectorizer = TfidfVectorizer(max_df = 0.9, max_features = 1000, stop_words='english')

Построение моделей:

In [10]:
count_vectorizer.fit(trainDF['text'])

xtrain_count =  count_vectorizer.transform(train_x)
xvalid_count =  count_vectorizer.transform(valid_x)

classifier = linear_model.LogisticRegression()
classifier.fit(xtrain_count, train_y)
predictions_CV = classifier.predict(xvalid_count)

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [11]:
tfidf_vectorizer.fit(trainDF['text'])

xtrain_count =  tfidf_vectorizer.transform(train_x)
xvalid_count =  tfidf_vectorizer.transform(valid_x)

classifier = linear_model.LogisticRegression()
classifier.fit(xtrain_count, train_y)
predictions_TF = classifier.predict(xvalid_count)

In [12]:
print(f'accuracy_score count_vectorizer №1: {accuracy_score(valid_y, predictions_CV)}')
print(f'accuracy_score tfidf_vectorizer №1: {accuracy_score(valid_y, predictions_TF)}')

accuracy_score count_vectorizer №1: 0.8216
accuracy_score tfidf_vectorizer №1: 0.8304

Уменьшим количество признаков:

In [13]:
count_vectorizer = CountVectorizer(max_df = 0.9, max_features = 500, stop_words='english')
tfidf_vectorizer = TfidfVectorizer(max_df = 0.9, max_features = 500, stop_words='english')

count_vectorizer.fit(trainDF['text'])

xtrain_count =  count_vectorizer.transform(train_x)
xvalid_count =  count_vectorizer.transform(valid_x)

classifier = linear_model.LogisticRegression()
classifier.fit(xtrain_count, train_y)
predictions_CV_2 = classifier.predict(xvalid_count)

tfidf_vectorizer.fit(trainDF['text'])

xtrain_count =  tfidf_vectorizer.transform(train_x)
xvalid_count =  tfidf_vectorizer.transform(valid_x)

classifier = linear_model.LogisticRegression()
classifier.fit(xtrain_count, train_y)
predictions_TF_2 = classifier.predict(xvalid_count)

print(f'accuracy_score count_vectorizer №1: {accuracy_score(valid_y, predictions_CV)}')
print(f'accuracy_score tfidf_vectorizer №1: {accuracy_score(valid_y, predictions_TF)}')
print(f'accuracy_score count_vectorizer features = 500: {accuracy_score(valid_y, predictions_CV_2)}')
print(f'accuracy_score tfidf_vectorizer features = 500: {accuracy_score(valid_y, predictions_TF_2)}')

accuracy_score count_vectorizer №1: 0.8216
accuracy_score tfidf_vectorizer №1: 0.8304
accuracy_score count_vectorizer features = 500: 0.8092
accuracy_score tfidf_vectorizer features = 500: 0.8104

Как видно из результатов, уменьшение количества признаков отрицательно повлияло на accuracy.

In [14]:
count_vectorizer = CountVectorizer(max_df = 0.9, max_features = 1000, stop_words='english')
tfidf_vectorizer = TfidfVectorizer(max_df = 0.9, max_features = 1000, stop_words='english')

pca = PCA(n_components=500)

count_vectorizer.fit(trainDF['text'])

xtrain_count =  count_vectorizer.transform(train_x)
xvalid_count =  count_vectorizer.transform(valid_x)
xtrain_PCA =  pca.fit_transform(xtrain_count.toarray())
xvalid_PCA =  pca.fit_transform(xvalid_count.toarray())

classifier = linear_model.LogisticRegression()
classifier.fit(xtrain_PCA, train_y)
predictions_CV_3 = classifier.predict(xvalid_PCA)

tfidf_vectorizer.fit(trainDF['text'])

xtrain_count =  tfidf_vectorizer.transform(train_x)
xvalid_count =  tfidf_vectorizer.transform(valid_x)
xtrain_PCA =  pca.fit_transform(xtrain_count.toarray())
xvalid_PCA =  pca.fit_transform(xvalid_count.toarray())

classifier = linear_model.LogisticRegression()
classifier.fit(xtrain_PCA, train_y)
predictions_TF_3 = classifier.predict(xvalid_PCA)

print(f'accuracy_score count_vectorizer №1: {accuracy_score(valid_y, predictions_CV)}')
print(f'accuracy_score tfidf_vectorizer №1: {accuracy_score(valid_y, predictions_TF)}')
print(f'accuracy_score count_vectorizer features = 500: {accuracy_score(valid_y, predictions_CV_2)}')
print(f'accuracy_score tfidf_vectorizer features = 500: {accuracy_score(valid_y, predictions_TF_2)}')
print(f'accuracy_score count_vectorizer PCA: {accuracy_score(valid_y, predictions_CV_3)}')
print(f'accuracy_score tfidf_vectorizer PCA: {accuracy_score(valid_y, predictions_TF_3)}')

accuracy_score count_vectorizer №1: 0.8216
accuracy_score tfidf_vectorizer №1: 0.8304
accuracy_score count_vectorizer features = 500: 0.8092
accuracy_score tfidf_vectorizer features = 500: 0.8104
accuracy_score count_vectorizer PCA: 0.466
accuracy_score tfidf_vectorizer PCA: 0.534

Как видно из результатов, применение PCA для уменишения размерности значительно ухудшило первоначальную точность.